<?php
/**
 * Copyright © 2017 Acaldeira, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Acaldeira\SimplePay\Block\Info\SimplePay
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($block->getInfo()->getAdditionalInformation()): ?>
    <?php if ($block->getNotes()): ?>
        <p><?php echo $block->escapeHtml(__('Notes: %1', $block->getNotes())) ?></p>
    <?php endif; ?>
<?php endif; ?>
